# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 337c7d9fb80efbb0bc742186dffd7634525313bd462c2dd6f3990ff7f96cd4e3a7411dc27bab970f961126b7df4344bf0169ae49665743e70c8df7609889ade5

test:
  secret_key_base: e752c7df67919c29209892f63dd3a9e5d3a7db66f4e6e3867d4ef331f86f879773f14c642eb9d5099427d0b7bb6d9772263f29c074429e4bb03915a2566a3f5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
